name: "Pixi-Pack Action"
description: "Use pixi-pack to create packed environments and installers"
author: ehrenfeu
branding:
  icon: 'upload'
  color: 'green'

inputs:
  environment:
    description: "Environment to pack"
    required: false
    default: 'default'
  platform:
    description: "Target platform for the environment (e.g., linux-64, osx-64, win-64)"
    required: false
  version:
    description: "Version string to embed in the output filename. Defaults to github.ref_name."
    default: ""
  pixi-pack-version:
    description: "Version of pixi-pack to use"
    required: false
    default: '0.7.6'

runs:
  using: "composite"
  steps:
  # 1) Install Pixi (using prefix-dev/setup-pixi)
  - name: Install Pixi
    uses: prefix-dev/setup-pixi@v0.9.4
    with:
      pixi-version: v0.67.2
      cache: true

  # - run: pixi run test

  # - name: foo
  #   uses: prefix-dev/setup-pixi@v0.8.3
  #   with:
  #     runInstall: false

  # 2) Install pixi-pack & rattler-build globally via pixi
  - name: Install pixi-pack
    run: pixi global install pixi-pack==${{ inputs.pixi-pack-version }}
    shell: bash

  # 4) Run pixi-pack with optional --inject
  - name: Run pixi-pack
    run: |
      echo "==> Packing environment for platform: ${{ inputs.platform }}"

      PACK_CMD="pixi-pack --environment '${{ inputs.environment }}' --create-executable "

      if [ -n "${{ inputs.platform }}" ]; then
        echo "Adding --platform flag: ${{ inputs.platform }}"
        PACK_CMD="$PACK_CMD --platform '${{ inputs.platform }}'"
      fi

      echo "Running: $PACK_CMD"
      eval "$PACK_CMD"
    shell: bash

  # 5) Rename the output file
  - name: Rename output file
    run: |
      OUTPUT_FILE=$(ls -1 | grep -E 'environment\.(sh|ps1)' | head -n 1)
      if [ -z "$OUTPUT_FILE" ]; then
        echo "No output file found matching pattern"
        exit 1
      fi
      VERSION="${{ inputs.version }}"
      if [ -z "$VERSION" ]; then
        VERSION="${{ github.ref_name }}"
      fi

      filename=$(basename -- "$OUTPUT_FILE")
      extension="${filename##*.}"
      NEW_NAME="${{ github.event.repository.name }}-$VERSION-${{ inputs.platform }}.${extension}"
      echo "Renaming $OUTPUT_FILE → $NEW_NAME"
      mv "$OUTPUT_FILE" "$NEW_NAME"
    shell: bash
